package sjtu.yhapter.reader.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import sjtu.yhapter.reader.model.pojo.Annotation;

import sjtu.yhapter.reader.model.dao.AnnotationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig annotationDaoConfig;

    private final AnnotationDao annotationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        annotationDaoConfig = daoConfigMap.get(AnnotationDao.class).clone();
        annotationDaoConfig.initIdentityScope(type);

        annotationDao = new AnnotationDao(annotationDaoConfig, this);

        registerDao(Annotation.class, annotationDao);
    }
    
    public void clear() {
        annotationDaoConfig.clearIdentityScope();
    }

    public AnnotationDao getAnnotationDao() {
        return annotationDao;
    }

}
