package sjtu.yhapter.ias.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import sjtu.yhapter.ias.model.pojo.TeachClass;
import sjtu.yhapter.ias.model.pojo.Book;
import sjtu.yhapter.ias.model.pojo.DownloadTask;

import sjtu.yhapter.ias.model.dao.TeachClassDao;
import sjtu.yhapter.ias.model.dao.BookDao;
import sjtu.yhapter.ias.model.dao.DownloadTaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig teachClassDaoConfig;
    private final DaoConfig bookDaoConfig;
    private final DaoConfig downloadTaskDaoConfig;

    private final TeachClassDao teachClassDao;
    private final BookDao bookDao;
    private final DownloadTaskDao downloadTaskDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        teachClassDaoConfig = daoConfigMap.get(TeachClassDao.class).clone();
        teachClassDaoConfig.initIdentityScope(type);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        downloadTaskDaoConfig = daoConfigMap.get(DownloadTaskDao.class).clone();
        downloadTaskDaoConfig.initIdentityScope(type);

        teachClassDao = new TeachClassDao(teachClassDaoConfig, this);
        bookDao = new BookDao(bookDaoConfig, this);
        downloadTaskDao = new DownloadTaskDao(downloadTaskDaoConfig, this);

        registerDao(TeachClass.class, teachClassDao);
        registerDao(Book.class, bookDao);
        registerDao(DownloadTask.class, downloadTaskDao);
    }
    
    public void clear() {
        teachClassDaoConfig.clearIdentityScope();
        bookDaoConfig.clearIdentityScope();
        downloadTaskDaoConfig.clearIdentityScope();
    }

    public TeachClassDao getTeachClassDao() {
        return teachClassDao;
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public DownloadTaskDao getDownloadTaskDao() {
        return downloadTaskDao;
    }

}
